blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.ArticleList.as_view(), name='home'),
    path('page/<int:page>', views.ArticleList.as_view(), name='home'),
    path('article/<slug:slug>', views.ArticleDetail.as_view(), name='detail'),
    path('category/<slug:slug>', views.CategoryList.as_view(), name='category'),   
    path('category/<slug:slug>/page/<int:page>', views.CategoryList.as_view(), name='category'),
    path('author/<username>', views.AuthorList.as_view(), name='author'),   
    path('author/<slug:username>/page/<int:page>', views.AuthorList.as_view(), name='author'),
    path('preview/<int:pk>', views.ArticlePreview.as_view(), name='preview'),
    
    
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('blog.urls')),
    path ('accounts/', include('accounts.urls')),
    path('comment/', include('comment.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    
    # Reset Password
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from accounts.models import CustomUser
from comment.models import Comment
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.urls import reverse
from django.utils import timezone


# managers
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')


class CategoryManager(models.Manager):
    def published(self):
        return self.filter(status=True)


class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL, related_name='children', verbose_name='subcateogry')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, )
    status = models.BooleanField(max_length=200, verbose_name='Be visible')
    position = models.IntegerField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['position']
        verbose_name_plural = 'Categories'

    objects = CategoryManager()


class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField()

class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
        ('i', 'Investigation'),
        ('b', 'Back')
    )
    title = models.CharField(max_length=200)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='articles')
    slug = models.SlugField(max_length=200, unique=True, )
    category = models.ManyToManyField("blog.category", related_name='article')
    description = models.TextField()
    thumbnail = models.ImageField(upload_to='images')
    published_at = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_special = models.BooleanField(default=False, verbose_name='Special Article')
    status = models.CharField(max_length=200, choices=STATUS_CHOICES, default='i')
    comments = GenericRelation(Comment)
    hits = models.ManyToManyField(IPAddress, through="ArticleHit", blank=True, related_name="hits")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("accounts:home")

    def category_to_str(self):
        return ", ".join([category.title for category in self.category.published()])
    category_to_str.short_description = 'categories'

    class Meta:
        ordering = ['-published_at']

    objects = ArticleManager()


class ArticleHit(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IPAddress, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    

blog/views.py
from datetime import datetime, timedelta

from accounts.mixins import AuthorAccessMixin
from accounts.models import CustomUser
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView

from blog.models import Article, Category


# Create your views here.
# based on FBV
class ArticleList(ListView):
    last_month = datetime.today() - timedelta(days=30)
    queryset = Article.objects.published().annotate(
        count=Count("hits", filter=Q(articlehit__created_at__gt=last_month))
        ).order_by('-count', '-published_at')
    queryset = Article.objects.published()
    template_name = 'blog/index.html'
    context_object_name = 'articles'
    paginate_by = 2


class ArticleDetail(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        article = get_object_or_404(Article.objects.published(), slug=slug)
        ip_address = self.request.user.ip_address 
        if ip_address not in article.hits.all():
            article.hits.add(ip_address)
        return article
    template_name = 'blog/detail.html'
    context_object_name = 'article'
    
 


class ArticlePreview(AuthorAccessMixin, DetailView):
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk=pk)
    template_name = 'blog/detail.html'
    context_object_name = 'article'
    

class CategoryList(ListView):
    paginate_by = 2
    template_name = 'blog/category.html'
    context_object_name = 'articles'

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.published(), slug=slug)
        return category.article.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context


class AuthorList(ListView):
    paginate_by = 2
    template_name = 'blog/author_articles.html'
    context_object_name = 'articles'

    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(CustomUser, username=username)
        return author.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context

comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

blog/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

blog/templates/blog/author_articles.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title  %} Home {% endblock title  %}
{% block main_content %}

    <!-- Page Header-->
    <header class="masthead" style="background-image: url('{% static 'blog/assets/img/home-bg.jpg' %}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Blog News</h1>
                        <span class="subheading">Be aware what is happening in the world</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            <h3 class='alert alert-primary text-center' > Author : {{author.get_full_name}} </h3>
            {% for article in articles %}
                <div class="post-preview">
                    <a href="{% url 'blog:detail' article.slug %}">
                        <h2 class="post-title">{{article.title}}</h2>
                        <h3 class="post-subtitle">{{article.description | truncatewords:30}}</h3>
                    </a>
                    <p class="post-meta">
                        Posted by <a href="{% url 'blog:author' article.author.username %}">{{article.author}}</a> on {{article.published_at}}
                    </p>
                    <div>
                        {% for cat in article.category.published %}
                            <a href=#>#{{cat.title}} </a>
                        {% endfor %}
                    </div>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            {% endfor %}
            <!-- Pager-->
            {% if is_paginated %}
            <div class="clearfix pager-botton mb-4 ml-4">
                {% if page_obj.has_previous %}<a class="btn  btn-primary text-uppercase ml-2 " href="{% url 'blog:author' author.username page_obj.previous_page_number %}">Older Posts →</a>{% endif %}
                {% if page_obj.has_next %}<a class="btn btn-primary text-uppercase ml-4 " href="{% url 'blog:author' author.username page_obj.next_page_number%}">Newer Posts →</a>{% endif %}
            </div>
        {% endif %} 
        </div>
    </div>
</div>
{% endblock%}

blog/templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog News - {% block title %}{% endblock title %}</title>
        <link rel="icon" type="{% static 'blog/image/x-icon' %}" href="{% static 'blog/assets/favicon.ico' %}">
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'blog/css/custom.css' %}" rel="stylesheet" />
        <!-- star rating -->
        <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">

    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blog:home' %}">Blog News</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                {% category_navbar %}
            </div>
        </nav>
        
        

        {% block main_content%}
        <!-- Page Header-->
        <!-- Main Content-->
        {% endblock main_content%}

        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js'%}"></script>
        <!--star rating-->
        <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    </body>
</html>

blog/templates/blog/category.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title  %} Home {% endblock title  %}
{% block main_content %}

    <!-- Page Header-->
    <header class="masthead" style="background-image: url('{% static 'blog/assets/img/home-bg.jpg' %}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Blog News</h1>
                        <span class="subheading">Be aware what is happening in the world</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            <h3 class='alert alert-primary text-center' > {{category.title}} </h3>
            {% for article in articles %}
                <div class="post-preview">
                    <a href="{% url 'blog:detail' article.slug %}">
                        <h2 class="post-title">{{article.title}}</h2>
                        <h3 class="post-subtitle">{{article.description | truncatewords:30}}</h3>
                    </a>
                    <p class="post-meta">
                        Posted by <a href="{% url 'blog:author' article.author.username %}">{{article.author}}</a> on {{article.published_at}}
                    </p>
                    <div>
                        {% for cat in article.category.published %}
                            <a href=#>#{{cat.title}} </a>
                        {% endfor %}
                    </div>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            {% endfor %}
            <!-- Pager-->
            {% if is_paginated %}
            <div class="clearfix pager-botton mb-4 ml-4">
                {% if page_obj.has_previous %}<a class="btn  btn-primary text-uppercase ml-2 " href="{% url 'blog:category' category.slug page_obj.previous_page_number %}">Older Posts →</a>{% endif %}
                {% if page_obj.has_next %}<a class="btn btn-primary text-uppercase ml-4 " href="{% url 'blog:category' category.slug page_obj.next_page_number%}">Newer Posts →</a>{% endif %}
            </div>
        {% endif %} 
        </div>
    </div>
</div>
{% endblock%}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load ratings %}
{% load comment_tags %}  {# Loading the template tag #}
{% include_bootstrap %}
{% block title %} {{article.title}}  {% endblock title %}
{% block main_content %}  
<!--Post Header -->
<header class="masthead" style="background-image: url('{{article.thumbnail.url}}')">
   <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
         <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="site-heading">
               <h1 class= 'title' id='post-title'> {{article.title}}</h1>
               {% ratings article %}  
               <div> views : {{ article.hits.count }}</div>
            </div>
         </div>
      </div>
   </div>
</header>
<article class="mb-4">
   <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
         <div class="col-md-10 col-lg-8 col-xl-7">
            {% if article.is_special %} 
            {% if  user.is_authenticated and user.is_special_user  or user.is_superuser or user == article.author %}
            {{article.description | safe | linebreaks}}
            {% else %}
            {{article.description |striptags|truncatewords:20}}
            <p class='alert alert-warning'> This is a special User. You have to <a href="#" class='alert-link'> buy Premium account</a> 
               to access this article
            </p>
            {% endif %}
            {% else %}
            {{article.description | safe | linebreaks}}
            {% endif %}           
            {% render_comments article request %} 
            {% include_bootstrap %}
         </div>
      </div>
   </div>
</article>
{% endblock main_content %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}
{% load ratings %}
{% load base_tags %}
{% block title  %} Home {% endblock title  %}
{% block main_content %}
<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static 'blog/assets/img/home-bg.jpg' %}')">
   <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="site-heading">
               <h1>Blog News</h1>
               <span class="subheading">Be aware what is happening in the world</span>
            </div>
         </div>
      </div>
   </div>
</header>

<div class="container">
   <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
         {% block header %}{% endblock header %}
         {% popular_articles %}
         <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
               <!-- Post preview-->
               {% for article in articles %}
               <div class="post-preview">
                  <a href="{% url 'blog:detail' article.slug %}">
                     <div>
                        <h2 class="post-title " style="display: inline-block" >{{article.title}}</h2>
                        {% if article.is_special %}<span class="badge alert-danger "style="vertical-align: top">Special</span>{% endif %}
                     </div>
                  </a>
                  {% ratings article %} 
                  <h3 class="post-subtitle">{{article.description |striptags|truncatewords:20}}</h3>
                  <p class="post-meta">
                     Posted by <a href="{% url 'blog:author' article.author.username %}">{{article.author}}</a> on {{article.published_at}}
                  </p>
                  <div>
                     {% for cat in article.category.all  %}
                     <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}} </a>
                     {% endfor %}
                  </div>
                  view: {{article.hits.count}}
               </div>
               <!-- Divider-->
               <hr class="my-4" />
               {% endfor %}
               <!-- Pager-->
               {% if is_paginated %}
               <div class="clearfix pager-botton mb-4 ml-4">
                  {% if page_obj.has_previous %}<a class="btn  btn-primary text-uppercase ml-2 " href="{% url 'blog:home' page_obj.previous_page_number %}">Older Posts →</a>{% endif %}
                  {% if page_obj.has_next %}<a class="btn btn-primary text-uppercase ml-4 " href="{% url 'blog:home' page_obj.next_page_number%}">Newer Posts →</a>{% endif %}
               </div>
               {% endif %}    
            </div>
         </div>
      </div>
   </div>
 
</div>


{% endblock%}